[
    {
        "content": "<p>Reading <code>roc-for-elm-programmers.md</code>, the only thing I could find about runtime exceptions is the numeric overflow. Are panic/aborts exposed to the app code anywhere else?</p>",
        "id": 258587726,
        "sender_full_name": "Shritesh Bhattarai",
        "timestamp": 1634838140
    },
    {
        "content": "<p>In roc, if there is a panic, it is sent directly to the platform/host and the app doesn't see it. Otherwise an error is returned to the app. Like in the case of getting an element from a list, you can receive an error that the index was out of bounds</p>",
        "id": 258588805,
        "sender_full_name": "Brendan Hansknecht",
        "timestamp": 1634838515
    },
    {
        "content": "<p>The distinction is essentially recoverable vs unrecoverable errors. In some cases, you can opt into recieving an error instead of panicing. For example, doing an addition that explicitly checks for overflow.</p>",
        "id": 258589394,
        "sender_full_name": "Brendan Hansknecht",
        "timestamp": 1634838758
    },
    {
        "content": "<p>Of course, when a host receives a panic, it doesn't have to crash. It can just clean up and continue executing.</p>",
        "id": 258589612,
        "sender_full_name": "Brendan Hansknecht",
        "timestamp": 1634838845
    },
    {
        "content": "<p>In the example of addition, these are \"throwing\" vs result-ing functions, right?</p>",
        "id": 258592087,
        "sender_full_name": "Shritesh Bhattarai",
        "timestamp": 1634839780
    },
    {
        "content": "<p>Also, is there like a \"panic\" or \"abort\" function available in userspace?</p>",
        "id": 258592280,
        "sender_full_name": "Shritesh Bhattarai",
        "timestamp": 1634839853
    },
    {
        "content": "<p>there is not, though I guess you could just cause an overflow and that would cause a panic and control is given to the platform</p>",
        "id": 258592361,
        "sender_full_name": "Folkert de Vries",
        "timestamp": 1634839888
    },
    {
        "content": "<p>Ah! So, runtime exceptions really are just effects, albeit implicit.</p>",
        "id": 258593100,
        "sender_full_name": "Shritesh Bhattarai",
        "timestamp": 1634840217
    },
    {
        "content": "<p>That is a very interesting way to word it...but I guess.</p>",
        "id": 258593168,
        "sender_full_name": "Brendan Hansknecht",
        "timestamp": 1634840254
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"452038\">Shritesh Bhattarai</span> has marked this topic as resolved.</p>",
        "id": 258595227,
        "sender_full_name": "Notification Bot",
        "timestamp": 1634841040
    }
]