[
    {
        "content": "<p>i am very new to roc. in all the examples the errors were handled in the caller function. what if I wanna handle it in the same function where error happens and try other code paths instead?</p>",
        "id": 452846014,
        "sender_full_name": "katro",
        "timestamp": 1721485799
    },
    {
        "content": "<p>Hi <span class=\"user-mention\" data-user-id=\"671820\">@katro</span>,<br>\nAssuming you want to handle a Task that has encountered an error you can use <code>Task.result!</code> like <a href=\"https://github.com/roc-lang/examples/blob/553640f46c223d636f7cfa70d97d2e91b0822147/examples/Tasks/main.roc#L69\">here</a>. Does that answer your question?</p>",
        "id": 452847449,
        "sender_full_name": "Anton",
        "timestamp": 1721486823
    },
    {
        "content": "<p>oh yeah. thatâ€™s it. thanks a lot.</p>",
        "id": 452848359,
        "sender_full_name": "katro",
        "timestamp": 1721487538
    }
]